# Generated by Django 6.0.3 on 2026-05-24 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_rollo_ubicacion_salidarepuesto_orden_movimientorollo_and_more'),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='rollo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='bodega.rollo'),
        ),
    ]
