# Generated by Django 6.0.3 on 2026-05-07 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='area',
            field=models.CharField(choices=[('electrico', 'Eléctrico'), ('tapiceria', 'Tapicería'), ('llantas', 'Llantas'), ('soldadura', 'Soldadura'), ('mecanica_general', 'Mecánica General')], default='mecanica_general', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='mecanico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.conductor'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.vehiculo'),
        ),
    ]
