# Generated by Django 6.0.3 on 2026-05-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_ordentrabajo_area_ordentrabajo_mecanico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='SalidaRepuestoTaller',
        ),
    ]
