# Generated by Django 6.0.3 on 2026-05-24 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_add_orden_trabajo_to_salida'),
        ('taller', '0004_mecanico_alter_ordentrabajo_vehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('entregado', 'Entregado'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'db_table': 'rollo',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ubicacion',
            },
        ),
        migrations.AddField(
            model_name='salidarepuesto',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_repuestos', to='taller.ordentrabajo'),
        ),
        migrations.CreateModel(
            name='MovimientoRollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('traslado', 'Traslado')], max_length=20)),
                ('cantidad', models.IntegerField(default=1)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('rollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bodega.rollo')),
            ],
            options={
                'db_table': 'movimiento_rollo',
            },
        ),
        migrations.AddField(
            model_name='rollo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollos', to='bodega.ubicacion'),
        ),
    ]
