# Generated by Django 6.0.3 on 2026-05-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_rollo_ubicacion_salidarepuesto_orden_movimientorollo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientorollo',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('traslado', 'Traslado')], max_length=20),
        ),
    ]
